### ISSUE TITLE
Question: Option to create ArtifactoryClient.create(url, userId, password) using API Key

### ISSUE THREAD

**Issue by hungvlam** [jfrog/artifactory-client-java#194]
I have downloaded artifactory-java-client-0.10.jar and follow the examples to download and upload the artifacts.   The example is below.  I'm wondering if instead of using "password" to create a connection to Artifactory Repo, I'm wondering if I could use API key instead.  I don't see such option in the API.  Am I missing something here?  Thanks.

Artifactory artifactory = ArtifactoryClient.create(url, userId, password)
InputStream is = artifactory.repository(repository).download("test.zip").doDownload()

**Comment by fritaly** [comment]
I think if you use your API key as your password and any user, this should work. It works when I tested with a generated token as my password.

Can you try ?

**Comment by hungvlam** [comment]
Thanks @fritaly.  It works. I actually use "" for userID with the apiKey.
