### ISSUE TITLE
There isn't version 2.6.2 in maven central repository

### ISSUE THREAD

**Issue by Zerozzzz** [jfrog/artifactory-client-java#202]
Hi Sir,there isn't version 2.6.2 in maven central repository,just version 0.16. When I set dependency with version 0.16，my program can't find ArtifactoryClientBuilder class.

**Comment by eyalbe4** [comment]
@Zerozzzz,
We stopped publishing the client to maven central a long time ago. All versions are available for resolution in jcenter

**Comment by Zerozzzz** [comment]
@eyalbe4 Thanks
