### ISSUE TITLE
RepositoryHandle#isFolder throws checked Exception 'HttpResponseException' without 'throws' clause

### ISSUE THREAD

**Issue by Flugtiger** [jfrog/artifactory-client-java#216]
The method isFolder in Interface RepositoryHandle throws an HttpResponseException (e.g. if the specified path does not exist in the repository) but since this exception is thrown behind the reflection layer, it is not specified in a throws clause.

Now, when using RepositoryHandle#isFolder, the HttpResponseException cannot be catched directly as this would lead to a compile time error "unreachable catch block":
![image](https://user-images.githubusercontent.com/3149624/44847998-72061900-ac55-11e8-823d-5d0d26ed1dd0.png)

Nevertheless the exception gets thrown, as demonstrated by the following stack trace:
![image](https://user-images.githubusercontent.com/3149624/44848080-c01b1c80-ac55-11e8-968e-6936655fd4e9.png)

A workaround could looks like this:
![image](https://user-images.githubusercontent.com/3149624/44848112-de811800-ac55-11e8-810c-7e5b2eb2a228.png)

**Comment by dodie** [comment]
This indeed results in a compile error. Opened a PR to declare the checked IOException that the implementation can throw.
