### ISSUE TITLE
how to close debug log?

### ISSUE THREAD

**Issue by out0fmemory** [jfrog/artifactory-client-java#217]
now release version contains so much log output,how to close this

**Comment by out0fmemory** [comment]
resolved by code blew:

((Logger)LoggerFactory.getLogger("org.apache.http")).setLevel(Level.ERROR);
        ((Logger)LoggerFactory.getLogger("org.apache.http.headers")).setLevel(Level.ERROR);
        ((Logger)LoggerFactory.getLogger("org.apache.http.wire")).setLevel(Level.ERROR);

**Comment by eyalbe4** [comment]
Thanks for sharing this information @out0fmemory!
This may be helpful for other.
