### ISSUE TITLE
there is no dependency in maven central

### ISSUE THREAD

**Issue by taojintianxia** [jfrog/artifactory-client-java#228]
#### I put the following maven dependency in my pom file , however , there is no corresponding dependency in maven central : https://repo.maven.apache.org/maven2/org/jfrog/artifactory/client/artifactory-java-client-services/
```
<dependency>
    <groupId>org.jfrog.artifactory.client</groupId>
    <artifactId>artifactory-java-client-services</artifactId>
    <version>2.6.2</version>
</dependency>
```

**Comment by LeiYangGH** [comment]
i can download it.

**Comment by eyalbe4** [comment]
@taojintianxia,
The *artifactory-cliebt-java* library is distributed through **jcenter** - 
https://jcenter.bintray.com/org/jfrog/artifactory/client/

**Comment by vdotjansen** [comment]
Issue can be closed as 2.9.2 is released on maven central. 2.10.0 is missing though.

**Comment by yahavi** [comment]
@vdotjansen
Thanks for reporting this issue.
We published at this moment 2.10.0 to Maven Central. The version is expected to be indexed in Maven Central in a few hours.

**Comment by hannesa2** [comment]
Sorry, my build.gradle only find it when I use `jcenter()`. 
With `mavenCentral()` alone, it doesn't find it

**Comment by yahavi** [comment]
@hannesa2 what is your Artifactory Java client version? Above 2.10.0 it should be in maven central

**Comment by hannesa2** [comment]
Ahh, sorry I forgot to mention, it's
`implementation 'org.jfrog.artifactory.client:artifactory-java-client-services:2.13.0'`
https://github.com/jfrog/artifactory-client-java/issues/362

**Comment by yahavi** [comment]
Hi @hannesa2,
The Java client 2.13.0 is in Maven Central, see https://mvnrepository.com/artifact/org.jfrog.artifactory.client/artifactory-java-client-services/2.13.0.

#362 looks like a different issue. I suggest we'll continue the conversation there.
