### ISSUE TITLE
I wanted to use Jfrog Java Client in java 1.7 version

### ISSUE THREAD

**Issue by khirodAsurion** [jfrog/artifactory-client-java#250]
jFrogJava Client jdk requirement

**Comment by eyalbe4** [comment]
@khirodAsurion,
JDK 7 is no longer supported.
I guess you can try and build the client sources with JDK 7 and if code changes are needed, fork the project and make the changes.

**Comment by khirodAsurion** [comment]
Hello,
I want to run the jFrogJava Client from a java 1.7 version system . Is that possible?

**Comment by khirodAsurion** [comment]
Thanks @eyalbe4
