### ISSUE TITLE
Add support for the helm repository type

### ISSUE THREAD

**Issue by glockhart** [jfrog/artifactory-client-java#252]
I have a PR ready for this that I'll open once the legal types give approval for signing the CLA

**Comment by eyalbe4** [comment]
Thanks @glockhart!

**Comment by yahavi** [comment]
@glockhart 
2.8.6 is released. This version includes you PR: https://github.com/jfrog/artifactory-client-java/pull/255 - Feel free to upgrade.
We'd appreciate your feedback for that!

**Comment by dodie** [comment]
I've just tried 2.8.6 for the Helm support, and it works nicely! Thanks!
