### ISSUE TITLE
builderFrom factory methods does not handle customProperties, xraySettings and cliendTlsCertificate

### ISSUE THREAD

**Issue by dodie** [jfrog/artifactory-client-java#260]
When I create a new builder based on an existing repository, some parameters are not set. For example:

```
RemoteRepository newRemoteRepository = artifactory.repositories().builders().builderFrom(myRepository).build();

newRemoteRepository.getClientTlsCertificate(); // null
newRemoteRepository.getXraySettings(); // null
newRemoteRepository.getCustomProperties() // null
```
I think these fields should be also addressed by the factories.

**Comment by eyalbe4** [comment]
@dodie,
Would you like to fix this by creating a pull request?

**Comment by dodie** [comment]
Hey @eyalbe4 ,

Sure! I was just wandering if not setting these properties are intentional or not.
I'll open a PR with the changes.

Thanks,
David

**Comment by eyalbe4** [comment]
Thanks @dodie!

**Comment by yahavi** [comment]
@dodie 
Artifactory Java client 2.9.2 is released and available on Maven Central.

**Comment by dodie** [comment]
Thank you!
