### ISSUE TITLE
Starting with 2.8.5, the artifact grew from 217kb to 8,7Mb

### ISSUE THREAD

**Issue by fprumbau** [jfrog/artifactory-client-java#261]
Hi,

  we just tried to from update to

<dependency>
  <groupId>org.jfrog.artifactory.client</groupId>
  <artifactId>artifactory-java-client-services</artifactId>
  <version>2.8.5</version>
</dependency>

(from 2.8.4) 

Now our application doesn't start anymore because 2.8.5 packages a lot of stuff like slf4j in the package. Is this correct or is it a packaging error?

**Comment by danhyun** [comment]
We just got bit by this as well, there's manual shading going on here https://github.com/jfrog/artifactory-client-java/blob/master/services/build.gradle#L51

I'm not sure what the intention is here with manually adding every runtime jar but this forces users to choose `artifactory-java-client-services` over their preferred or required logging frameworks/bridges.

**Comment by danhyun** [comment]
The offending commit, https://github.com/jfrog/artifactory-client-java/commit/6672ddf717ef1195da2d7aac07340d3b3a893322

Seems that there's no longer any distinction between fatJar and normal jar, users are now forced to always consume the fat jar.

**Comment by danhyun** [comment]
Related https://github.com/jfrog/artifactory-client-java/issues/262

**Comment by yahavi** [comment]
@fprumbau 
2.8.6 is released - Feel free to upgrade.
We'd appreciate you feedback for that.

**Comment by fprumbau** [comment]
We upgraded, everything OK again, thank you.
