### ISSUE TITLE
Get RepositorySettingsImpl for a PackageType

### ISSUE THREAD

**Issue by dodie** [jfrog/artifactory-client-java#267]
The [PackageTypeImpl](https://github.com/jfrog/artifactory-client-java/blob/1eb832e154f9e55e3fd205fe5524881403c26be6/services/src/main/java/org/jfrog/artifactory/client/model/impl/PackageTypeImpl.java) enum contains all supported repository types. Each `RepositorySettingsImpl` contains a reference to a value of this enum (e.g: [MavenRepositorySettingsImpl#getPackageType](https://github.com/jfrog/artifactory-client-java/blob/bf5f123124fd42730b9e3f22e457bfc8b28053d1/services/src/main/java/org/jfrog/artifactory/client/model/repository/settings/impl/MavenRepositorySettingsImpl.java#L42).

So, it's quite easy to get the `PackageType` for a given `RepositorySettings` object. Is it possible the other way around? I'm building a CLI application that takes the repository type as an argument. Based on that, I'd like to create the appropriate `RepositorySettings` object. Currently I have my own enum, similar to `PackageTypeImpl` that has all the corresponding `RepositorySettingsImpl`s for each type.

It would be nice if this would be supported by the library out of the box, as this seems to be a quite common requirement.

**Comment by eyalbe4** [comment]
@dodie,
Feel free to add this through a pull request. 
If there are other things that you'll need for the new CLI, please let us know.

**Comment by dodie** [comment]
@eyalbe4 , okay, thanks!

**Comment by dodie** [comment]
Hi @eyalbe4 ,

May I ask if you had the chance to review the PR?

Thanks in advance,
David

**Comment by eyalbe4** [comment]
PR merge @dodie.
Thank you!

**Comment by dodie** [comment]
Hi @eyalbe4 !

Are there plans regarding the next release of the library?

Thanks and cheers,
David
