### ISSUE TITLE
How to get a list of files in a folder?

### ISSUE THREAD

**Issue by asherbar** [jfrog/artifactory-client-java#285]
I'm looking for the equivalent of the [File List](https://www.jfrog.com/confluence/display/JFROG/Artifactory+REST+API#ArtifactoryRESTAPI-FileList) API. Something along the lines of:

    artifactory = ArtifactoryClientBuilder.create()
            .setUrl(url)
            .setUsername(userName)
            .setPassword(password)
            .build();
    List<String> filesInFolder = artifactory.repository(repository).folder(folderPath).list();

 Does it exist? What's the alternative if not?

This seems related to #10 but the information there is outdated.

**Comment by eyalbe4** [comment]
@asherbar,
The **Folder** interface includes a **getChildren()** method. Have you tried that?
(See in README the *Folder Info* section how to get the details of a specific folder in Artifactory).

**Comment by asherbar** [comment]
Yes that seems right. Thanks!

**Comment by asherbar** [comment]
@eyalbe4 the File List API also returns information for every file (specifically., the `lastModified` property) while for the items in `getChildren` this property is null. What's the way to get a list with all the information?

**Comment by eyalbe4** [comment]
@asherbar,
The following API:
```artifactory.repository("repoName").folder("path/to/folder").info()```
invokes the ```/api/storage/repoName/path/to/folder``` which returns the following response foramt:
```
{
  "repo" : "generic-local",
  "path" : "/xray",
  "created" : "2020-04-19T10:22:13.057+03:00",
  "createdBy" : "admin",
  "lastModified" : "2020-04-19T10:22:13.057+03:00",
  "modifiedBy" : "admin",
  "lastUpdated" : "2020-04-19T10:22:13.057+03:00",
  "children" : [ {
    "uri" : "/commands",
    "folder" : true
  }, {
    "uri" : "/cli.go",
    "folder" : false
  } ],
  "uri" : "http://localhost:8081/artifactory/api/storage/generic-local/xray"
}
```
which indeed does not include the metadata for the children.
I believe you have two options:
1. Invoke the same API separately for each child item t get this metadata.
2. Use [AQL](https://www.jfrog.com/confluence/display/JFROG/Artifactory+Query+Language). This hasn't yet been documented in the README, by this library does include AQL support. Till the usage is properly documented, you can look at the code in the **AqlQueryBuilderTest** class to see how to use it.

**Comment by asherbar** [comment]
A separate API for every child seems wasteful so I tried the following AQL:
`items.find({"path": "< folderPath>", "repo": "<repoName>"})` but I get empty results. What am I missing?

**Comment by asherbar** [comment]
After building the AQL string with AqlQueryBuilder, how do I execute the query?
