### ISSUE TITLE
How can i get NPM dependency in Jfrog with Rest api or our client?

### ISSUE THREAD

**Issue by Leo0426** [jfrog/artifactory-client-java#290]
I've already upload NPM artifact use 'npm pubilish' command.

Then i saw some npm info on jfrog web ui, such as 'General', 'NPM info'....

![image](https://user-images.githubusercontent.com/19218360/87941590-f3772680-cacd-11ea-9af5-9505aa16dfab.png)

But , i cann't find the rest api for get this information.

Please, help me with this.

**Comment by Leo0426** [comment]
No one answer.Closed.

**Comment by eyalbe4** [comment]
My apologies for missing your question @Leo0426!
The name and the version of the npm package can be retrieved using the AQL REST API. These are saved as plain artifact properties in Artifactory. Please refer to the AQL documentation for guidance on how to query artifacts properties. You'll also find in the documentation an older, property search REST API. As for the licensing info, it is produced in JFrog Xray. I believe there's currently no public REST API exposed by Xray to retrieve this info directly. 
Please let me know if this helps  and feel free to share with me your end goal, and I'll try to assist further.

**Comment by Leo0426** [comment]
> My apologies for missing your question @Leo0426!
> The name and the version of the npm package can be retrieved using the AQL REST API. These are saved as plain artifact properties in Artifactory. Please refer to the AQL documentation for guidance on how to query artifacts properties. You'll also find in the documentation an older, property search REST API. As for the licensing info, it is produced in JFrog Xray. I believe there's currently no public REST API exposed by Xray to retrieve this info directly.
> Please let me know if this helps and feel free to share with me your end goal, and I'll try to assist further.

Thank you for your patience to explain, I used AQL but I still can't get the information I need. Maybe the information I want is generated in Xray, as you said, but I don't want to build X-ray service. In the end, I gave up exploration, because the time cost is too high.Still thank you very much.

**Comment by eyalbe4** [comment]
Sure. Let us know if we can be of further assistance.
