### ISSUE TITLE
Unable to implment Artifactory Rest API in intellij java springboot service - Cannot access groovy.lang.GroovyObject

### ISSUE THREAD

**Issue by muditjha** [jfrog/artifactory-client-java#358]
ArtifactoryRequest repositoryRequest = new ArtifactoryRequestImpl().apiUrl("api/repositories")
        .method(ArtifactoryRequest.Method.GET)
        .responseType(ArtifactoryRequest.ContentType.JSON);
ArtifactoryResponse response = artifactory.restCall(repositoryRequest);

Using this implementation shows compilation error- **Cannot access groovy.lang.GroovyObject** How do I fix this?

**Comment by jcoste-orange** [comment]
Same issue for me. Anyone has a workaround?

**Comment by muditjha** [comment]
Add following dep to pom.xml -

        <dependency>
            <groupId>org.jfrog.artifactory.client</groupId>
            <artifactId>artifactory-java-client-services</artifactId>
            <version>2.13.1</version>
        </dependency>
        <dependency>
            <groupId>org.apache.groovy</groupId>
            <artifactId>groovy</artifactId>
            <version>4.0.6</version>
        </dependency>

**Comment by rkrisztian** [comment]
That is a workaround, not a fix. Why is this ticket closed? If Groovy is needed it should be an explicit dependency.
